import { formatCurrency, formatMiles } from './format';
import type { VentureRollup } from './reportCalculations';

function escapeHtml(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

export function buildPnlReportHtml(params: {
  title: string;
  rangeLabel: string;
  rollups: VentureRollup[];
  totals: Omit<VentureRollup, 'ventureId' | 'ventureName'>;
}): string {
  const { title, rangeLabel, rollups, totals } = params;

  const rows = rollups
    .map(
      (r) => `
        <tr>
          <td>${escapeHtml(r.ventureName)}</td>
          <td class="num">${formatMiles(r.totalMiles)}</td>
          <td class="num">${formatCurrency(r.totalDeduction)}</td>
          <td class="num">${formatCurrency(r.totalExpenses)}</td>
          <td class="num strong">${formatCurrency(r.netDeductible)}</td>
        </tr>`
    )
    .join('');

  return `
    <html>
      <head>
        <meta charset="utf-8" />
        <style>
          body { font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 32px; color: #1a1d23; }
          h1 { font-size: 20px; margin-bottom: 4px; }
          .subtitle { color: #6b7280; font-size: 13px; margin-bottom: 24px; }
          table { width: 100%; border-collapse: collapse; font-size: 13px; }
          th { text-align: left; border-bottom: 2px solid #1a1d23; padding: 8px 6px; font-size: 12px; text-transform: uppercase; color: #6b7280; }
          td { padding: 8px 6px; border-bottom: 1px solid #e2e5ea; }
          td.num { text-align: right; }
          td.strong, th.num.strong { font-weight: 700; }
          tfoot td { font-weight: 700; border-top: 2px solid #1a1d23; border-bottom: none; }
          .footer { margin-top: 24px; font-size: 11px; color: #6b7280; }
        </style>
      </head>
      <body>
        <h1>${escapeHtml(title)}</h1>
        <div class="subtitle">${escapeHtml(rangeLabel)}</div>
        <table>
          <thead>
            <tr>
              <th>Venture</th>
              <th class="num">Miles</th>
              <th class="num">Mileage Deduction</th>
              <th class="num">Expenses</th>
              <th class="num">Net Deductible</th>
            </tr>
          </thead>
          <tbody>
            ${rows}
          </tbody>
          <tfoot>
            <tr>
              <td>Total</td>
              <td class="num">${formatMiles(totals.totalMiles)}</td>
              <td class="num">${formatCurrency(totals.totalDeduction)}</td>
              <td class="num">${formatCurrency(totals.totalExpenses)}</td>
              <td class="num">${formatCurrency(totals.netDeductible)}</td>
            </tr>
          </tfoot>
        </table>
        <div class="footer">Generated by Mileage &amp; Tax Tracker. Net Deductible = mileage deduction + logged expenses.</div>
      </body>
    </html>`;
}
